version: "3"
services:
  db:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: events
    volumes:
      - ./pgdata:/var/lib/postgressql/data
    ports:
      - "1040:5432"
